## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np
# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Hobart,AU,-42.8794,147.3294,46.11,81,75,1.99,broken clouds
1,1,Rajanpur,PK,29.1035,70.3250,91.26,50,85,14.00,overcast clouds
2,2,Qaanaaq,GL,77.4840,-69.3632,42.37,62,23,3.85,few clouds
3,3,Borovoy,RU,55.4333,86.0833,67.28,77,0,4.47,clear sky
4,4,Avarua,CK,-21.2078,-159.7750,78.85,69,20,11.50,few clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 80

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
4,4,Avarua,CK,-21.2078,-159.7750,78.85,69,20,11.50,few clouds
7,7,Tricase,IT,39.9304,18.3553,79.95,62,0,8.86,clear sky
12,12,Izumo,JP,35.3667,132.7667,78.75,83,0,8.05,clear sky
14,14,Anloga,GH,5.7947,0.8973,77.22,84,64,11.74,broken clouds
29,29,Kampong Chhnang,KH,12.1667,104.5500,76.84,85,100,3.74,overcast clouds
34,34,Saint-Francois,FR,46.4154,3.9054,76.17,82,0,3.44,clear sky
37,37,Siocon,PH,7.7061,122.1353,79.21,84,99,4.45,overcast clouds
41,41,Hasaki,JP,35.7333,140.8333,79.29,78,0,3.56,clear sky
42,42,Wuda,CN,39.4994,106.7117,74.07,67,1,21.05,clear sky
46,46,Rikitea,PF,-23.1203,-134.9692,71.33,59,71,13.58,broken clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                208
City                   208
Country                208
Lat                    208
Lng                    208
Max Temp               208
Humidity               208
Cloudiness             208
Wind Speed             208
Current Description    208
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
#preferred_cities_clean_df = preferred_cities_df.dropna

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = np.nan
hotel_df.head(40)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Avarua,CK,78.85,few clouds,-21.2078,-159.7750,NaN
7,Tricase,IT,79.95,clear sky,39.9304,18.3553,NaN
12,Izumo,JP,78.75,clear sky,35.3667,132.7667,NaN
14,Anloga,GH,77.22,broken clouds,5.7947,0.8973,NaN
29,Kampong Chhnang,KH,76.84,overcast clouds,12.1667,104.5500,NaN
34,Saint-Francois,FR,76.17,clear sky,46.4154,3.9054,NaN
37,Siocon,PH,79.21,overcast clouds,7.7061,122.1353,NaN
41,Hasaki,JP,79.29,clear sky,35.7333,140.8333,NaN
42,Wuda,CN,74.07,clear sky,39.4994,106.7117,NaN
46,Rikitea,PF,71.33,broken clouds,-23.1203,-134.9692,NaN
47,Vaini,TO,78.96,scattered clouds,-21.2000,-175.2000,NaN
55,Agropoli,IT,78.28,clear sky,40.3469,14.9966,NaN
60,Ashta,IN,73.81,broken clouds,23.0167,76.7167,NaN
63,Remontnoye,RU,70.21,overcast clouds,46.5614,43.6501,NaN
65,Ribeira Grande,PT,71.60,overcast clouds,38.5167,-28.7000,NaN
68,Jadu,LY,73.74,clear sky,31.9530,12.0261,NaN
74,Bandarbeyla,SO,77.52,few clouds,9.4942,50.8122,NaN
81,Tual,ID,79.75,overcast clouds,-5.6667,132.7500,NaN
85,Bafoulabe,ML,77.65,broken clouds,13.8065,-10.8321,NaN
87,Bayan,CN,78.06,scattered clouds,46.0833,127.4000,NaN
89,Anqing,CN,77.38,clear sky,30.5092,117.0506,NaN
92,Takaungu,KE,75.69,few clouds,-3.6837,39.8566,NaN
99,Yellowknife,CA,70.32,light intensity shower rain,62.4560,-114.3525,NaN
103,Sri Aman,MY,77.09,overcast clouds,1.2376,111.4621,NaN
105,Broome,US,76.69,clear sky,42.2506,-75.8330,NaN
114,Senneterre,CA,73.62,overcast clouds,48.3835,-77.2328,NaN
115,Imeni Poliny Osipenko,RU,79.27,broken clouds,52.4201,136.4853,NaN
117,Puerto Carreno,CO,77.54,overcast clouds,6.1890,-67.4859,NaN
118,Hambantota,LK,79.56,overcast clouds,6.1241,81.1185,NaN
121,Albany,US,75.45,scattered clouds,42.6001,-73.9662,NaN
126,Jamestown,US,76.59,clear sky,42.0970,-79.2353,NaN
130,Ca Mau,VN,77.36,overcast clouds,9.1769,105.1500,NaN
135,Fort Nelson,CA,71.19,broken clouds,58.8053,-122.7002,NaN
136,Vao,NC,71.04,clear sky,-22.6667,167.4833,NaN
139,Dakar,SN,78.93,broken clouds,14.6937,-17.4441,NaN
143,Bengkulu,ID,74.61,broken clouds,-3.8004,102.2655,NaN
145,Savelugu,GH,79.54,overcast clouds,9.6244,-0.8253,NaN
152,Ponta Do Sol,PT,72.23,clear sky,32.6667,-17.1000,NaN
159,Vanimo,PG,78.28,overcast clouds,-2.6741,141.3028,NaN
163,Calabozo,VE,77.61,broken clouds,8.9242,-67.4293,NaN

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]       
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(subset = ['Hotel Name'])
clean_hotel_df.head(40)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
4,Avarua,CK,78.85,few clouds,-21.2078,-159.7750,Paradise Inn
7,Tricase,IT,79.95,clear sky,39.9304,18.3553,Hotel Adriatico
12,Izumo,JP,78.75,clear sky,35.3667,132.7667,Toyoko-Inn Izumoshi ekimae
14,Anloga,GH,77.22,broken clouds,5.7947,0.8973,Pin Drop Hotel
29,Kampong Chhnang,KH,76.84,overcast clouds,12.1667,104.5500,រមណីយដ្ឋាន ទឹកធ្លាក់ស្រែអំពិល
34,Saint-Francois,FR,76.17,clear sky,46.4154,3.9054,Manoir Du Bonheur
37,Siocon,PH,79.21,overcast clouds,7.7061,122.1353,ABS Hotel
41,Hasaki,JP,79.29,clear sky,35.7333,140.8333,Hotel Sunrise Choshi
42,Wuda,CN,74.07,clear sky,39.4994,106.7117,Grape Sightseeing Garden
46,Rikitea,PF,71.33,broken clouds,-23.1203,-134.9692,People ThankYou
47,Vaini,TO,78.96,scattered clouds,-21.2000,-175.2000,Keleti Beach Resort
55,Agropoli,IT,78.28,clear sky,40.3469,14.9966,B&B Baia di Trentova
60,Ashta,IN,73.81,broken clouds,23.0167,76.7167,Digambar Jain Dharamshala
63,Remontnoye,RU,70.21,overcast clouds,46.5614,43.6501,Remontnoye
65,Ribeira Grande,PT,71.60,overcast clouds,38.5167,-28.7000,Quinta da Meia Eira
68,Jadu,LY,73.74,clear sky,31.9530,12.0261,امياس للصرافة
74,Bandarbeyla,SO,77.52,few clouds,9.4942,50.8122,JABIR HOTEL
81,Tual,ID,79.75,overcast clouds,-5.6667,132.7500,Grand Vilia Hotel
87,Bayan,CN,78.06,scattered clouds,46.0833,127.4000,Wanhao Inn
89,Anqing,CN,77.38,clear sky,30.5092,117.0506,Hongtian Hotel
92,Takaungu,KE,75.69,few clouds,-3.6837,39.8566,Takaungu House
99,Yellowknife,CA,70.32,light intensity shower rain,62.4560,-114.3525,The Explorer Hotel
103,Sri Aman,MY,77.09,overcast clouds,1.2376,111.4621,Seri Simanggang Hotel
105,Broome,US,76.69,clear sky,42.2506,-75.8330,Chenango Valley State Park
114,Senneterre,CA,73.62,overcast clouds,48.3835,-77.2328,Motel Senabi
115,Imeni Poliny Osipenko,RU,79.27,broken clouds,52.4201,136.4853,Yubileynaya
117,Puerto Carreno,CO,77.54,overcast clouds,6.1890,-67.4859,Casa Hotel Victoria
118,Hambantota,LK,79.56,overcast clouds,6.1241,81.1185,Bungalow 63
126,Jamestown,US,76.59,clear sky,42.0970,-79.2353,Hampton Inn & Suites Jamestown
130,Ca Mau,VN,77.36,overcast clouds,9.1769,105.1500,Khách Sạn Mường Thanh Luxury Cà Mau
135,Fort Nelson,CA,71.19,broken clouds,58.8053,-122.7002,The Fort Nelson Hotel
136,Vao,NC,71.04,clear sky,-22.6667,167.4833,Hotel Kou-Bugny
139,Dakar,SN,78.93,broken clouds,14.6937,-17.4441,Redface Studios Meublés
143,Bengkulu,ID,74.61,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
145,Savelugu,GH,79.54,overcast clouds,9.6244,-0.8253,Yoo Naa's Palace
152,Ponta Do Sol,PT,72.23,clear sky,32.6667,-17.1000,Hotel do Campo
159,Vanimo,PG,78.28,overcast clouds,-2.6741,141.3028,Vahmoneh Lodge Vanimo
163,Calabozo,VE,77.61,broken clouds,8.9242,-67.4293,Hotel Giardini
165,Tabuk,PH,78.96,overcast clouds,17.4189,121.4443,Golden Berries Hotel and Convention
167,Yining,CN,76.50,scattered clouds,29.0361,114.5636,Xiushui Hotel

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>Location</dt><dd>{City} / {Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

# 11a. Add a marker layer for each city to the map.
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))